// File: registers.v
// Generated by MyHDL 0.11
// Date: Fri Nov 26 23:03:15 2021


`timescale 1ns/10ps

module registers (
    rs1,
    rs2,
    rd,
    rs1_out,
    rs2_out,
    clk,
    enable,
    data
);


input [4:0] rs1;
input [4:0] rs2;
input [4:0] rd;
output [31:0] rs1_out;
reg [31:0] rs1_out;
output [31:0] rs2_out;
reg [31:0] rs2_out;
input clk;
input enable;
input [31:0] data;

reg [31:0] Reg [0:32-1];



always @(posedge clk) begin: REGISTERS_REGISTER_SUB
    rs1_out <= Reg[rs1];
    rs2_out <= Reg[rs2];
    if ((enable == 1)) begin
        Reg[rd] <= data;
    end
end

endmodule
