// File: andG.v
// Generated by MyHDL 0.11
// Date: Sat Nov 20 22:17:12 2021


`timescale 1ns/10ps

module andG (
    in1,
    in2,
    out
);


input [31:0] in1;
input [31:0] in2;
output out;
wire out;





assign out = (in1 & in2);

endmodule
