// File: andG.v
// Generated by MyHDL 0.11
// Date: Thu Nov 18 02:17:26 2021


`timescale 1ns/10ps

module andG (
    in1,
    in2,
    out
);


input in1;
input in2;
output out;
wire out;





assign out = (in1 & in2);

endmodule
