// File: ins_dec.v
// Generated by MyHDL 0.11
// Date: Thu Nov 18 01:54:58 2021


`timescale 1ns/10ps

module ins_dec (
    pass_bits,
    clk,
    opcode,
    rd,
    func3,
    rs1,
    rs2,
    func7,
    imm12,
    imm20
);


input [31:0] pass_bits;
input clk;
output [6:0] opcode;
reg [6:0] opcode;
output [4:0] rd;
reg [4:0] rd;
output [2:0] func3;
reg [2:0] func3;
output [4:0] rs1;
reg [4:0] rs1;
output [4:0] rs2;
reg [4:0] rs2;
output [6:0] func7;
reg [6:0] func7;
output [19:0] imm12;
reg [19:0] imm12;
output [11:0] imm20;
reg [11:0] imm20;




always @(posedge clk) begin: INS_DEC_DECODER
    opcode <= pass_bits[7-1:0];
    func3 <= pass_bits[15-1:12];
    func7 <= pass_bits[32-1:25];
    if ((pass_bits[7-1:0] == 51)) begin
        rd <= pass_bits[12-1:7];
        rs1 <= pass_bits[20-1:15];
        rs2 <= pass_bits[25-1:20];
    end
    else if ((pass_bits[7-1:0] == 19)) begin
        rd <= pass_bits[12-1:7];
        rs1 <= pass_bits[20-1:15];
        imm12 <= pass_bits[32-1:20];
    end
    else if (((pass_bits[7-1:0] == 3) || (pass_bits[7-1:0] == 103) || (pass_bits[7-1:0] == 115))) begin
        rd <= pass_bits[12-1:7];
        rs1 <= pass_bits[20-1:15];
        imm12 <= pass_bits[32-1:20];
    end
    else if ((pass_bits[7-1:0] == 35)) begin
        rs1 <= pass_bits[20-1:15];
        rs2 <= pass_bits[25-1:20];
        imm12 <= {pass_bits[32-1:25], pass_bits[12-1:7]};
    end
    else if ((pass_bits[7-1:0] == 99)) begin
        rs1 <= pass_bits[20-1:15];
        rs2 <= pass_bits[25-1:20];
        imm12 <= {pass_bits[32-1:31], pass_bits[8-1:7], pass_bits[31-1:25], pass_bits[12-1:8]};
    end
    else if (((pass_bits[7-1:0] == 55) || (pass_bits[7-1:0] == 23))) begin
        rd <= pass_bits[12-1:7];
        imm20 <= pass_bits[32-1:12];
    end
    else if ((pass_bits[7-1:0] == 111)) begin
        rd <= pass_bits[12-1:7];
        imm20 <= {pass_bits[31], pass_bits[20-1:12], pass_bits[20], pass_bits[31-1:21]};
    end
end

endmodule
