// File: pc.v
// Generated by MyHDL 0.11
// Date: Thu Nov 18 01:59:14 2021


`timescale 1ns/10ps

module pc (
    pass_input,
    out,
    reset,
    clk
);


input [13:0] pass_input;
output [13:0] out;
reg [13:0] out;
input reset;
input clk;




always @(posedge clk, posedge reset) begin: PC_PCBLOCK
    if (reset == 1) begin
        out <= 0;
    end
    else begin
        out <= pass_input;
    end
end

endmodule
