// File: extender.v
// Generated by MyHDL 0.11
// Date: Mon Nov 22 07:44:45 2021


`timescale 1ns/10ps

module extender (
    input_12or20,
    output32
);


input [19:0] input_12or20;
output [31:0] output32;
reg [31:0] output32;




always @(input_12or20) begin: EXTENDER_EXT
    output32[32-1:0] = input_12or20;
end

endmodule
