// File: mux2_1.v
// Generated by MyHDL 0.11
// Date: Fri Nov 26 23:10:46 2021


`timescale 1ns/10ps

module mux2_1 (
    sel,
    out,
    imm,
    rs2
);


input sel;
output [31:0] out;
reg [31:0] out;
input [31:0] imm;
input [31:0] rs2;




always @(rs2, sel, imm) begin: MUX2_1_MUX
    if ((sel == 0)) begin
        out = rs2;
    end
    else begin
        out = imm;
    end
end

endmodule
