// File: mux2_1.v
// Generated by MyHDL 0.11
// Date: Sun Nov 28 00:50:31 2021


`timescale 1ns/10ps

module mux2_1 (
    sel,
    out,
    imm,
    rs2
);


input sel;
output [31:0] out;
reg [31:0] out;
input [31:0] imm;
input [31:0] rs2;




always @(imm, sel, rs2) begin: MUX2_1_MUX
    if ((sel == 0)) begin
        out = rs2;
    end
    else begin
        out = imm;
    end
end

endmodule
