// File: mux_32to1.v
// Generated by MyHDL 0.11
// Date: Sat Nov 20 23:12:02 2021


`timescale 1ns/10ps

module mux_32to1 (
    sel,
    out,
    imm,
    rs2
);


input sel;
output [31:0] out;
reg [31:0] out;
input [31:0] imm;
input [31:0] rs2;




always @(sel, imm, rs2) begin: MUX_32TO1_MUX
    if ((sel == 0)) begin
        out = rs2;
    end
    else begin
        out = imm;
    end
end

endmodule
