// File: barrel_shifter.v
// Generated by MyHDL 0.11
// Date: Fri Nov 26 23:03:22 2021


`timescale 1ns/10ps

module barrel_shifter (
    load_value,
    load_input,
    shift_reg
);


output [31:0] load_value;
wire [31:0] load_value;
input [31:0] load_input;
input [1:0] shift_reg;





assign load_value = (load_input << shift_reg);

endmodule
