// File: PC_gen.v
// Generated by MyHDL 0.11
// Date: Sun Nov 21 06:42:52 2021


`timescale 1ns/10ps

module PC_gen (
    PC,
    imm,
    sel,
    out
);


input [31:0] PC;
input [31:0] imm;
input sel;
output [31:0] out;
reg [31:0] out;




always @(PC, sel, imm) begin: PC_GEN_GEN
    if ((sel == 0)) begin
        out = (PC + 4);
    end
    else begin
        out = (PC + imm);
    end
end

endmodule
