// File: PC_gen.v
// Generated by MyHDL 0.11
// Date: Fri Nov 26 22:58:01 2021


`timescale 1ns/10ps

module PC_gen (
    PC,
    rs1,
    imm,
    sel,
    out
);


input [31:0] PC;
input [31:0] rs1;
input [31:0] imm;
input [1:0] sel;
output [31:0] out;
reg [31:0] out;




always @(PC, imm, rs1, sel) begin: PC_GEN_GEN
    case (sel)
        'h0: begin
            out = (PC + 4);
        end
        'h1: begin
            out = (PC + imm);
        end
        default: begin
            out = (rs1 + imm);
        end
    endcase
end

endmodule
