// File: alu.v
// Generated by MyHDL 0.11
// Date: Sat Nov 20 23:27:51 2021


`timescale 1ns/10ps

module alu (
    a,
    b,
    sel,
    out
);


input [31:0] a;
input [31:0] b;
input [3:0] sel;
output [31:0] out;
reg [31:0] out;




always @(b, sel, a) begin: ALU_ALU
    case (sel)
        'h0: begin
            out = (a + b);
        end
        'h1: begin
            out = (a * b);
        end
        'h2: begin
            out = (a / b);
        end
        'h3: begin
            out = (a & b);
        end
        'h4: begin
            out = (a | b);
        end
        'h5: begin
            out = (a ^ b);
        end
        'h6: begin
            out = (a << b);
        end
        'h7: begin
            out = (a >>> b);
        end
        default: begin
            case (sel)
                'h8: begin
                    out = 1;
                end
                'h9: begin
                    out = 1;
                end
                'ha: begin
                    out = 1;
                end
                'hb: begin
                    out = 1;
                end
            endcase
        end
    endcase
end

endmodule
