// File: alu.v
// Generated by MyHDL 0.11
// Date: Mon Nov 22 18:33:38 2021


`timescale 1ns/10ps

module alu (
    a,
    b,
    sel,
    out
);


input [31:0] a;
input [31:0] b;
input [3:0] sel;
output [31:0] out;
reg [31:0] out;




always @(b, a, sel) begin: ALU_ALU
    case (sel)
        'h0: begin
            out = (a + b);
        end
        'h1: begin
            out = (a * b);
        end
        'h2: begin
            out = (a / b);
        end
        'h3: begin
            out = (a & b);
        end
        'h4: begin
            out = (a | b);
        end
        'h5: begin
            out = (a ^ b);
        end
        'h6: begin
            out = (a << b);
        end
        'h7: begin
            out = (a >>> b);
        end
        'h8: begin
            if ((a == b)) begin
                out = 1;
            end
            else begin
                out = 0;
            end
        end
        'h9: begin
            if ((a != b)) begin
                out = 1;
            end
            else begin
                out = 0;
            end
        end
        'ha: begin
            if ((a < b)) begin
                out = 1;
            end
            else begin
                out = 0;
            end
        end
        default: begin
            if ((a <= b)) begin
                out = 1;
            end
            else begin
                out = 0;
            end
        end
    endcase
end

endmodule
